# Generated by Django 6.0.3 on 2026-03-15 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CargaPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='presupuestos/')),
                ('hoja', models.CharField(blank=True, max_length=120)),
                ('total_registros', models.PositiveIntegerField(default=0)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_carga'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('rut', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('contacto', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('direccion', models.CharField(blank=True, max_length=255)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PersonalTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('cargo', models.CharField(max_length=150)),
                ('area', models.CharField(blank=True, max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=50)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_creado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RegistroPresupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila_origen', models.PositiveIntegerField()),
                ('fecha', models.DateField(blank=True, null=True)),
                ('fecha_texto', models.CharField(blank=True, max_length=120)),
                ('presupuesto', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('solicitante', models.CharField(blank=True, max_length=200)),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('nota_pedido', models.CharField(blank=True, max_length=255)),
                ('estado_oc', models.CharField(blank=True, max_length=120)),
                ('observacion_oc', models.TextField(blank=True)),
                ('recepcion', models.TextField(blank=True)),
                ('estado_recepcion', models.CharField(blank=True, max_length=120)),
                ('guia_despacho', models.CharField(blank=True, max_length=255)),
                ('factura', models.CharField(blank=True, max_length=255)),
                ('fecha_facturacion', models.DateField(blank=True, null=True)),
                ('fecha_facturacion_texto', models.CharField(blank=True, max_length=120)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('fecha_pago_texto', models.CharField(blank=True, max_length=120)),
                ('estado_manual', models.CharField(blank=True, choices=[('', 'Automatico segun flujo'), ('pendiente', 'Pendiente aprobacion'), ('en_proceso', 'Aceptado / En curso'), ('facturado', 'Realizado'), ('pagado', 'Pagado')], default='', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_actualizacion', models.DateTimeField(blank=True, null=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presupuestos_actualizados', to=settings.AUTH_USER_MODEL)),
                ('carga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='core.cargapresupuesto')),
            ],
            options={
                'ordering': ['-carga__fecha_carga', 'fila_origen'],
                'unique_together': {('carga', 'fila_origen')},
            },
        ),
        migrations.AddField(
            model_name='documento',
            name='presupuestos',
            field=models.ManyToManyField(blank=True, related_name='documentos', to='core.registropresupuesto'),
        ),
    ]
