# Generated by Django 6.0.3 on 2026-03-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cargapresupuesto_cliente_personaltrabajo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registropresupuesto',
            name='estado_manual',
            field=models.CharField(
                blank=True,
                choices=[
                    ('', 'Automático según flujo'),
                    ('pendiente', 'Pendiente de aprobación'),
                    ('en_proceso', 'Aceptado / En curso'),
                    ('facturado', 'Realizado'),
                    ('pagado', 'Pagado'),
                ],
                default='',
                max_length=20,
            ),
        ),
    ]
