# Generated by Django 6.0.3 on 2026-03-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_registropresupuesto_estado_manual'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='registropresupuesto',
            index=models.Index(fields=['presupuesto'], name='regpre_presupuesto_idx'),
        ),
        migrations.AddIndex(
            model_name='registropresupuesto',
            index=models.Index(fields=['nota_pedido'], name='regpre_nota_pedido_idx'),
        ),
        migrations.AddIndex(
            model_name='registropresupuesto',
            index=models.Index(fields=['factura'], name='regpre_factura_idx'),
        ),
        migrations.AddIndex(
            model_name='registropresupuesto',
            index=models.Index(fields=['fecha_pago'], name='regpre_fecha_pago_idx'),
        ),
        migrations.AddIndex(
            model_name='registropresupuesto',
            index=models.Index(fields=['fecha_facturacion'], name='regpre_fecha_fact_idx'),
        ),
        migrations.AddIndex(
            model_name='registropresupuesto',
            index=models.Index(fields=['estado_manual'], name='regpre_estado_manual_idx'),
        ),
    ]
