# Generated by Django 6.0.3 on 2026-03-16 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_trabajos_personal'),
    ]

    operations = [
        migrations.AddField(
            model_name='registropresupuesto',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presupuestos', to='core.cliente'),
        ),
        migrations.AddField(
            model_name='registropresupuesto',
            name='tipo_trabajo',
            field=models.CharField(blank=True, choices=[('instalacion', 'Instalacion electrica'), ('mantencion', 'Mantencion'), ('reparacion', 'Reparacion'), ('certificacion', 'Certificacion'), ('montaje', 'Montaje en obra'), ('otro', 'Otro')], max_length=30),
        ),
        migrations.AddField(
            model_name='registropresupuesto',
            name='ubicacion_obra',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
