# Generated by Django 6.0.3 on 2026-03-16 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_presupuesto_contexto_obra'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaltrabajo',
            name='afiliacion_mutualidad',
            field=models.FileField(blank=True, upload_to='personal/mutualidad/'),
        ),
        migrations.AddField(
            model_name='personaltrabajo',
            name='certificado_antecedentes',
            field=models.FileField(blank=True, upload_to='personal/antecedentes/'),
        ),
        migrations.AddField(
            model_name='personaltrabajo',
            name='certificado_fonasa',
            field=models.FileField(blank=True, upload_to='personal/fonasa/'),
        ),
        migrations.AddField(
            model_name='personaltrabajo',
            name='certificado_pago_afp',
            field=models.FileField(blank=True, upload_to='personal/afp/'),
        ),
        migrations.AddField(
            model_name='personaltrabajo',
            name='curriculum',
            field=models.FileField(blank=True, upload_to='personal/curriculum/'),
        ),
        migrations.AddField(
            model_name='personaltrabajo',
            name='examen_altura_espacio_confinado',
            field=models.FileField(blank=True, upload_to='personal/examenes/'),
        ),
    ]
